// Code generated by Slice Machine. DO NOT EDIT.

import CardBack from './CardBack/index.svelte';
import CardFront from './CardFront/index.svelte';

export const components = {
	card_back: CardBack,
	card_front: CardFront
};
