// Code generated by Slice Machine. DO NOT EDIT.

import PageContent from './PageContent/index.svelte';
import TestSlice from './TestSlice/index.svelte';

export const components = {
	page_content: PageContent,
	test_slice: TestSlice
};
