// Code generated by Slice Machine. DO NOT EDIT.

import BioText from './BioText/index.svelte';
import BlobImg from './BlobImg/index.svelte';
import HeadingText from './HeadingText/index.svelte';

export const components = {
	bio_text: BioText,
	blob_img: BlobImg,
	heading_text: HeadingText
};
