// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = CardFrontSlice | CardBackSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
	/**
	 * Slice Zone field in *page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *CardBack → Primary*
 */
export interface CardBackSliceDefaultPrimary {
	/**
	 * Picture field in *CardBack → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_back.primary.picture
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	picture: prismic.ImageField<never>;
}

/**
 * Primary content in *CardBack → Items*
 */
export interface CardBackSliceDefaultItem {
	/**
	 * InfoLine field in *CardBack → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_back.items[].infoline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	infoline: prismic.KeyTextField;
}

/**
 * Default variation for CardBack Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardBackSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CardBackSliceDefaultPrimary>,
	Simplify<CardBackSliceDefaultItem>
>;

/**
 * Slice variation for *CardBack*
 */
type CardBackSliceVariation = CardBackSliceDefault;

/**
 * CardBack Shared Slice
 *
 * - **API ID**: `card_back`
 * - **Description**: CardBack
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardBackSlice = prismic.SharedSlice<'card_back', CardBackSliceVariation>;

/**
 * Primary content in *CardFront → Primary*
 */
export interface CardFrontSliceDefaultPrimary {
	/**
	 * firstName field in *CardFront → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_front.primary.firstname
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	firstname: prismic.KeyTextField;

	/**
	 * lastName field in *CardFront → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_front.primary.lastname
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	lastname: prismic.KeyTextField;
}

/**
 * Default variation for CardFront Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardFrontSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CardFrontSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *CardFront*
 */
type CardFrontSliceVariation = CardFrontSliceDefault;

/**
 * CardFront Shared Slice
 *
 * - **API ID**: `card_front`
 * - **Description**: CardFront
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardFrontSlice = prismic.SharedSlice<'card_front', CardFrontSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			CardBackSlice,
			CardBackSliceDefaultPrimary,
			CardBackSliceDefaultItem,
			CardBackSliceVariation,
			CardBackSliceDefault,
			CardFrontSlice,
			CardFrontSliceDefaultPrimary,
			CardFrontSliceVariation,
			CardFrontSliceDefault
		};
	}
}
