// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = HeadingTextSlice | BlobImgSlice | BioTextSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
	/**
	 * Slice Zone field in *page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *BioText → Items*
 */
export interface BioTextSliceDefaultItem {
	/**
	 * bioline field in *BioText → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bio_text.items[].bioline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	bioline: prismic.KeyTextField;
}

/**
 * Default variation for BioText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BioTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	Simplify<BioTextSliceDefaultItem>
>;

/**
 * Slice variation for *BioText*
 */
type BioTextSliceVariation = BioTextSliceDefault;

/**
 * BioText Shared Slice
 *
 * - **API ID**: `bio_text`
 * - **Description**: BioText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BioTextSlice = prismic.SharedSlice<'bio_text', BioTextSliceVariation>;

/**
 * Primary content in *BlobImg → Primary*
 */
export interface BlobImgSliceDefaultPrimary {
	/**
	 * image field in *BlobImg → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blob_img.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for BlobImg Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlobImgSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BlobImgSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *BlobImg*
 */
type BlobImgSliceVariation = BlobImgSliceDefault;

/**
 * BlobImg Shared Slice
 *
 * - **API ID**: `blob_img`
 * - **Description**: BlobImg
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlobImgSlice = prismic.SharedSlice<'blob_img', BlobImgSliceVariation>;

/**
 * Primary content in *HeadingText → Primary*
 */
export interface HeadingTextSliceDefaultPrimary {
	/**
	 * text field in *HeadingText → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: heading_text.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;
}

/**
 * Default variation for HeadingText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeadingTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *HeadingText*
 */
type HeadingTextSliceVariation = HeadingTextSliceDefault;

/**
 * HeadingText Shared Slice
 *
 * - **API ID**: `heading_text`
 * - **Description**: HeadingText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingTextSlice = prismic.SharedSlice<'heading_text', HeadingTextSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			BioTextSlice,
			BioTextSliceDefaultItem,
			BioTextSliceVariation,
			BioTextSliceDefault,
			BlobImgSlice,
			BlobImgSliceDefaultPrimary,
			BlobImgSliceVariation,
			BlobImgSliceDefault,
			HeadingTextSlice,
			HeadingTextSliceDefaultPrimary,
			HeadingTextSliceVariation,
			HeadingTextSliceDefault
		};
	}
}
